services:
  app:
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .env
    # Menambahkan depends_on agar aplikasi menunggu database siap
    depends_on:
      - db

  db:
    image: postgres:15-alpine # Menggunakan image resmi PostgreSQL
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      # Mengekspos port database ke host (opsional, untuk debugging)
      - "5432:5432"
    volumes:
      # Membuat volume bernama 'db-data' untuk menyimpan data secara persisten
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: # Mendefinisikan volume yang akan kita gunakan