# Baris "version: '3.8'" telah dihapus
services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - SESSION_SECRET=${SESSION_SECRET} # Membaca dari shell/env file
    env_file:
      - .env # Menggunakan file .env